export const RECREATION_SAVE_REQUEST = 'RECREATION_SAVE_REQUEST';
export const RECREATION_SAVE_SUCCESS = 'RECREATION_SAVE_SUCCESS';
export const RECREATION_SAVE_FAIL = 'RECREATION_SAVE_FAIL';
export const RECREATTION_SAVE_RESET = 'RECREATTION_SAVE_RESET';

export const RECREATION_DELETE_REQUEST = 'RECREATION_DELETE_REQUEST';
export const RECREATION_DELETE_SUCCESS = 'RECREATION_DELETE_SUCCESS';
export const RECREATION_DELETE_FAIL = 'RECREATION_DELETE_FAIL';
export const RECREATION_DELETE_RESET = 'RECREATION_DELETE_RESET';

export const RECREATTION_LIST_REQUEST = 'RECREATTION_LIST_REQUEST';
export const RECREATTION_LIST_SUCCESS = 'RECREATTION_LIST_SUCCESS';
export const RECREATTION_LIST_FAIL = 'RECREATTION_LIST_FAIL';

export const RECREATION_QUERY_REQUEST = 'RECREATION_QUERY_REQUEST';
export const RECREATION_QUERY_SUCCESS = 'RECREATION_QUERY_SUCCESS';
export const RECREATION_QUERY_FAIL = 'RECREATION_QUERY_FAIL';