export const REFERENCE_SAVE_REQUEST = 'REFERENCE_SAVE_REQUEST';
export const REFERENCE_SAVE_SUCCESS = 'REFERENCE_SAVE_SUCCESS';
export const REFERENCE_SAVE_FAIL = 'REFERENCE_SAVE_FAIL';
export const REFERENCE_SAVE_RESET = 'REFERENCE_SAVE_RESET';


export const REFERENCE_DELETE_REQUEST = 'REFERENCE_DELETE_REQUEST';
export const REFERENCE_DELETE_SUCCESS = 'REFERENCE_DELETE_SUCCESS';
export const REFERENCE_DELETE_FAIL = 'REFERENCE_DELETE_FAIL';
export const REFERENCE_DELETE_RESET = 'REFERENCE_DELETE_RESET';

export const REFERENCE_LIST_REQUEST = 'REFERENCE_LIST_REQUEST';
export const REFERENCE_LIST_SUCCESS = 'REFERENCE_LIST_SUCCESS';
export const REFERENCE_LIST_FAIL = 'REFERENCE_LIST_FAIL';

// export const REFERENCE_DETAILS_REQUEST = 'REFERENCE_DETAILS_REQUEST';
// export const REFERENCE_DETAILS_SUCCESS = 'REFERENCE_DETAILS_SUCCESS';
// export const REFERENCE_DETAILS_FAIL = 'REFERENCE_DETAILS_FAIL';

export const REFERENCE_QUERY_REQUEST = 'REFERENCE_QUERY_REQUEST';
export const REFERENCE_QUERY_SUCCESS = 'REFERENCE_QUERY_SUCCESS';
export const REFERENCE_QUERY_FAIL = 'REFERENCE_QUERY_FAIL';


export const REFERENCE_RECREATION_LIST_QUERY_REQUEST = 'REFERENCE_RECREATION_LIST_QUERY_REQUEST';
export const REFERENCE_RECREATION_LIST_QUERY_SUCCESS = 'REFERENCE_RECREATION_LIST_QUERY_SUCCESS';
export const REFERENCE_RECREATION_LIST_QUERY_FAIL = 'REFERENCE_RECREATION_LIST_QUERY_FAIL';