export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_AVATAR_SAVE_REQUEST = 'USER_AVATAR_SAVE_REQUEST';
export const USER_AVATAR_SAVE_SUCCESS = 'USER_AVATAR_SAVE_SUCCESS';
export const USER_AVATAR_SAVE_FAIL = 'USER_AVATAR_SAVE_FAIL';
export const USER_AVATAR_SAVE_RESET = 'USER_AVATAR_SAVE_RESET';

export const USER_SELECT_FILE_TO_UPLOAD = 'USER_SELECT_FILE_TO_UPLOAD';
export const USER_UPLOAD_FILE_RESET = 'USER_UPLOAD_FILE_RESET';
export const USER_REMOVE_FILE_TO_UPLOAD = 'USER_REMOVE_FILE_TO_UPLOAD';

export const USER_QUERY_RECREATION_LIST_REQUEST = 'USER_QUERY_RECREATION_LIST_REQUEST';
export const USER_QUERY_RECREATION_LIST_SUCCESS = 'USER_QUERY_RECREATION_LIST_SUCCESS';
export const USER_QUERY_RECREATION_LIST_FAIL = 'USER_QUERY_RECREATION_LIST_FAIL';

export const USER_QUERY_REFERENCE_LIST_REQUEST = 'USER_QUERY_REFERENCE_LIST_REQUEST';
export const USER_QUERY_REFERENCE_LIST_SUCCESS = 'USER_QUERY_REFERENCE_LIST_SUCCESS';
export const USER_QUERY_REFERENCE_LIST_FAIL = 'USER_QUERY_REFERENCE_LIST_FAIL';